/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPIS.h"
#include "SPIS_SPI_UART.h"
#include "SPIS_PINS.h"
#include "SPIS_SPI_UART_PVT.h"
#include "SPIS_PVT.h"
#include "SPIS_BOOT.h"
#include "MOSI.h"
#include "MOSI_aliases.h"
#include "SCLK.h"
#include "SCLK_aliases.h"
#include "SwClock.h"
#include "Bootloadable_1.h"
#include "SS.h"
#include "SS_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "DISPLAY_Timer_INT.h"
#include "DISPLAY_Timer.h"
#include "MISO.h"
#include "MISO_aliases.h"
#include "Push_button.h"
#include "Push_button_aliases.h"
#include "PSoC_LED.h"
#include "PSoC_LED_aliases.h"
#include "SPIS_SCBCLK.h"
#include "SPIS_SCB_IRQ.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

